// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkHnd_coEw3bWmLlxLOnQtNwuI7eZDQC4',
    appId: '1:660506059205:web:ca5a29f250c63ac225ebac',
    messagingSenderId: '660506059205',
    projectId: 'dreamanellapp',
    authDomain: 'dreamanellapp.firebaseapp.com',
    storageBucket: 'dreamanellapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlDpKhYuMNN2qc_9_eZIATrE_TL3ZMNjA',
    appId: '1:660506059205:android:02d58b58d367f15625ebac',
    messagingSenderId: '660506059205',
    projectId: 'dreamanellapp',
    storageBucket: 'dreamanellapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ9hOP_FJxP9dfbf5knsGDFthTq3N02rw',
    appId: '1:660506059205:ios:f9d0023b9cc555c625ebac',
    messagingSenderId: '660506059205',
    projectId: 'dreamanellapp',
    storageBucket: 'dreamanellapp.appspot.com',
    iosClientId: '660506059205-h6c3ab8l20t7o0pmhmkimkmdvspujkme.apps.googleusercontent.com',
    iosBundleId: 'com.example.dreamanellaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ9hOP_FJxP9dfbf5knsGDFthTq3N02rw',
    appId: '1:660506059205:ios:f9d0023b9cc555c625ebac',
    messagingSenderId: '660506059205',
    projectId: 'dreamanellapp',
    storageBucket: 'dreamanellapp.appspot.com',
    iosClientId: '660506059205-h6c3ab8l20t7o0pmhmkimkmdvspujkme.apps.googleusercontent.com',
    iosBundleId: 'com.example.dreamanellaApp',
  );
}
